name: 'Plan'

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**'
  workflow_dispatch:
   inputs:
      dir:
        description: 'Directory with resources to be PLAN'
        required: true
        default: 'terraform'

jobs:
  terraform:
    name: 'plan'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    environment: plan

    defaults:
      run:
        shell: bash
        working-directory: "./terraform"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.2.6 
        terraform_wrapper: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request' 
      run: terraform plan -no-color -inpwdput=false
      continue-on-error: true